variables:
  rootfs: $(Build.SourcesDirectory)/product/rootfs.tar.xz
  product: product

steps:
- script: ./nano build image
  displayName: Build Buildroot container

- script: ./nano build rootfs
  displayName: Build Ghost

- script: ./nano pull rootfs && [[ -r $ROOTFS ]]
  displayName: Pull rootfs

- script: '[[ $(tar tf "$ROOTFS" | head -1) = ./ ]]'
  displayName: Test rootfs begins with root entry

- script: (( $(tar tf "$ROOTFS" | grep -Fxce ./usr/bin/node) == 1 ))
  displayName: Test rootfs contains Node binary

- script: docker build -t "$PRODUCT" product
  displayName: Import product image

- script: |
    mb=$(($(docker inspect -f '{{.Size}}' "$PRODUCT") / 1000000))
    echo Nano image size: ${mb}MB.
    ((mb)) && echo "##vso[task.setvariable variable=image size]$mb"
  displayName: Calculate image size

- script: '[[ $(docker run --rm "$PRODUCT" node -e ''console.log("foo")'') = foo ]]'
  displayName: Test Node

- script: |
    version=$(docker run --rm "$PRODUCT" node -v)
    echo Node.js version: $version
    echo "##vso[task.setvariable variable=node version]$version"
  displayName: Export Node version

- script: |
    version=$(tar xOf "$ROOTFS" ./usr/lib/node_modules/ghost/package.json | jq -r .version)
    echo Ghost version: $version
    echo "##vso[task.setvariable variable=ghost version]$version"
  displayName: Export Ghost version

- script: |
    mkdir -vp ${data=$HOME/ghost/data}
    namei -mo "$data"
    echo "##vso[task.setvariable variable=data]$data"

    docker run --rm -v "$data":/usr/lib/node_modules/ghost/content/data "$PRODUCT" knex-migrator init
    [[ -r $data/ghost.db ]]
  displayName: Generate new database

- script: '[[ $(file "$DATA/ghost.db") = *''SQLite 3.x database'' ]]'
  displayName: Verify database format

- script: git clone https://github.com/TryGhost/Casper.git "$DATA"/../themes/casper
  displayName: Download Casper

- script: |
    set -v
    docker run --rm -v "$DATA"/..:/var/ghost -dp ${address=127.0.0.1:2368}:2368 --name "$PRODUCT" "$PRODUCT"
    docker port "$PRODUCT"

    sleep 5
    docker logs "$PRODUCT"
    wget $address
    [[ $(file index.html) = *HTML\ document* ]]
  displayName: Run Ghost

- script: |
    wget -Otar https://github.com/cbroglie/mustache/releases/download/v1.0.1/mustache_1.0.1_linux_amd64.tar.gz
    tar xvf tar mustache
    [[ -x mustache ]]
  displayName: Install mustache

- script: |
    yaml="
      size: $IMAGE_SIZE
      version: $GHOST_VERSION
      node version: $NODE_VERSION"
    echo "$yaml"

    echo > product/README.md "$(./mustache product/README.md <<<"$yaml")"
  displayName: Template product readme

- script: |
    set -v

    git init
    git config user.name Azure
    git config user.email bilge+azure-bot@scriptfusion.com
    git config credential.helper store
    git remote add origin $(Build.Repository.Uri)
    echo '$(GIT_CREDENTIALS)' > ~/.git-credentials

    git pull --depth=1 origin "${branch=product/$(Build.SourceBranchName)}"

    cp -flv '$(Build.SourcesDirectory)'/product/* .

    git add .
    git commit -m 'Built product from $(Build.SourceVersion).' && git push origin HEAD:"$branch"
  displayName: Push product
  workingDirectory: $(Build.StagingDirectory)
